blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'
urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<slug:slug>/', views.PostDetailView.as_view(), name='post_detail'),
    # path('<slug:slug>/like/', views.like_post, name='post_like'),
    # path('<slug:slug>/comment/', views.comment_post, name='post_comment'),
    # path('<slug:slug>/rate/', views.rating_post, name='post_rate'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('', include('tourplan.urls', namespace='tourplan')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('chat/', include('chat.urls', namespace='chat')),
    path('game/', include('game.urls', namespace='game')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tourplan/urls.py
from django.urls import path
from . import views

app_name = 'tourplan'
urlpatterns = [
    path('', views.home_view, name='home_page'),
    path('tour/', views.tourplan_view, name='tourplan_list_page'),
    path('tour/<slug:slug>/', views.tourplan_view, name='tourplan_detail_page'),

    path('agency/', views.agency_view, name='agency_list_page'),
    path('hotel/', views.hotel_view, name='hotel_list_page'),
    path('restaurant/', views.restaurant_view, name='restaurant_list_page'),
    path('about/', views.about_view, name='about_page'),
    path('contact/', views.contact_view, name='contact_page'),

    path('map/', views.google_map, name='google_map_page')
]

tourplan/models/address.py
from django.db import models


class Location(models.Model):
    class DivisionChoices(models.TextChoices):
        BARISAL = 'BRS', 'Barisal'
        CHITTAGONG = 'CTG', 'Chittagong'
        DHAKA = 'DHK', 'Dhaka'
        Khulna = 'KLN', 'Khulna'
        MYMENSINGH = 'MMS', 'Mymensingh'
        RAJSHAHI = 'RJS', 'Rajshahi'
        RANGPUR = 'RGP', 'Rangpur'
        SYLHET = 'SYL', 'Sylhet'
    division = models.CharField(max_length=20, choices=DivisionChoices.choices)
    district = models.CharField(max_length=20)

    class Meta:
        verbose_name = 'Location'
        verbose_name_plural = 'Locations'

    def __str__(self):
        return f'{self.division} - {self.district}'

tourplan/models/agency.py
from django.db import models


class Agency(models.Model):
    name = models.CharField(max_length=120)
    details = models.TextField()
    weblink = models.URLField()
    rating = models.IntegerField()
    image = models.ImageField(upload_to='agency/')

    def __str__(self):
        return self.name

tourplan/models/hotels.py
from django.db import models
from django.utils.text import slugify
from .address import Location


class Hotel(models.Model):
    RATING_STATUS = (
        (1, "★☆☆☆☆"),
        (2, "★★☆☆☆"),
        (3, "★★★☆☆"),
        (4, "★★★★☆"),
        (5, "★★★★★"),
    )
    name = models.CharField(max_length=120)
    slug = models.SlugField(blank=True)
    details = models.CharField(max_length=200)
    address = models.ForeignKey(Location, on_delete=models.CASCADE, related_name='hotels')
    rating = models.IntegerField(choices=RATING_STATUS)
    weblink = models.URLField()
    image = models.ImageField(upload_to='hotel/')
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

tourplan/models/restaurants.py
from django.db import models
from .address import Location


class Restaurant(models.Model):
    RATING_CHOICES = [
        (1, 'One'),
        (2, 'Two'),
        (3, 'Three'),
        (4, 'Four'),
        (5, 'Five'),
    ]
    name = models.CharField(max_length=120)
    place = models.CharField(max_length=120)
    address = models.ForeignKey(Location, on_delete=models.DO_NOTHING, related_name='restaurants')
    weblink = models.URLField(blank=True, null=True)
    description = models.CharField(max_length=120)
    rating = models.IntegerField(choices=RATING_CHOICES)
    created_at = models.DateField(auto_now_add=True)
    image = models.ImageField(upload_to='restaurants/')


    def __str__(self):
        return self.name

tourplan/models/tour.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from .address import Location


class Category(models.Model):
    parent = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True, related_name='children')
    name = models.CharField(max_length=20, unique=True)

    def __str__(self):
        return self.name


class TourPlace(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='+')
    address = models.ForeignKey(Location, on_delete=models.DO_NOTHING, related_name='tourplaces')
    name = models.CharField(max_length=120, blank=True)
    slug = models.SlugField(max_length=120, unique=True)
    short_description = models.CharField(max_length=200)
    long_description = models.TextField()
    cover_photo = models.ImageField(upload_to='cover/', validators=[])
    created_at = models.DateField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('tourplan:tourplan_detail_page', args=[self.slug])

tourplan/views.py
from django.db.models import Q
from django.shortcuts import render, redirect
from tourplan.models import *


def home_view(request):
    tourplans = TourPlace.objects.all().order_by('-id')[:3]
    hotels = Hotel.objects.all().order_by('-id')[:3]
    agencies = Agency.objects.all().order_by('-id')[:3]
    restaurants = Restaurant.objects.all().order_by('-id')[:3]
    context = {
        'tourplans': tourplans,
        'hotels': hotels,
        'agencies': agencies,
        'restaurants': restaurants,
        'user': request.user
    }
    return render(request, 'tourplan/home.html', context=context)


def tourplan_view(request, slug=None):
    tourplans = TourPlace.objects.all()
    if slug:
        tourplan = TourPlace.objects.filter(slug=slug)
        return render(request, 'tourplan/list/tourplan_list.html', {'tourplan': tourplan})
    else:
        return render(request, 'tourplan/list/tourplan_list.html', {'tourplans': tourplans})


def hotel_view(request):
    hotels = Hotel.objects.all()
    return render(request, 'tourplan/list/hotel_list.html', {'hotels': hotels})


def agency_view(request):
    agencies = Agency.objects.all()
    return render(request, 'tourplan/list/agency_list.html', {'agencies': agencies})


def restaurant_view(request):
    restaurants = Restaurant.objects.all()
    return render(request, 'tourplan/list/restaurant_list.html', {'restaurants': restaurants})


def about_view(request):
    return render(request, 'tourplan/about.html')


def contact_view(request):
    return render(request, 'tourplan/contact.html')


def google_map(request):
    tourplans = TourPlace.objects.all()
    return render(request, 'tourplan/tourplan.html', {'tourplans': tourplans})

tourplan/templates/tourplan/about.html
{% extends '_base.html' %}

{% block container %}
    {% if not user.is_authenticated %}
        {% include 'navbar.html' %}
    {% else %}
        {% include 'navbar_in_logged_state.html' %}
    {% endif %}

    <!-- Breadcrumb -->
    <nav class="container py-4 mb-2 my-lg-3" aria-label="breadcrumb">
        <ol class="breadcrumb mb-0">
            <li class="breadcrumb-item">
                <a href="{% url 'tourplan:home_page' %}"><i class="bx bx-home-alt fs-lg me-1"></i>Home</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">About</li>
        </ol>
    </nav>


    <!-- About company -->
    <section class="container pb-5 mb-md-2 mb-lg-4">
        <h1 class="border-bottom pb-4">Who We Are</h1>
        <div class="row pt-2 pt-md-3">
            <div class="col-md-6">
                <p class="fs-lg pe-lg-4 mb-1 mb-lg-4">There are many variations of passages of Lorem Ipsum available,
                    but the majority have suffered alteration in some form, by injected humour, or randomised words
                    which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you
                    need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum
                    generators on the Internet tend to repeat predefined chunks as necessary, making this the first true
                    generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of
                    model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum
                    is therefore always free from repetition, injected humour, or non-characteristic words etc.</p>
            </div>
            <div class="col-md-6">
                <p class="fs-lg ps-lg-4 mb-1 mb-lg-4">On the other hand, we denounce with righteous indignation and
                    dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded
                    by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame
                    belongs to those who fail in their duty through weakness of will, which is the same as saying
                    through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish. In a
                    free hour,  every pleasure is to be welcomed and every pain avoided. But in certain
                    circumstances and owing to the claims of duty or the obligations of business it will frequently
                    occur that pleasures have to be repudiated and annoyances accepted.</p>
            </div>
        </div>
    </section>

    <!-- Team (Slider) -->
    <section class="container pt-lg-2 pb-2">
        <h2 class="h1 text-center pb-md-1 mb-1 mb-sm-3">Our Leaders</h2>
        <div class="swiper-wrapper ">
            <!-- Item -->
            <div class="swiper-slide py-3" style="width: 250px; margin: auto">
                <div class="card card-body card-hover bg-light border-0 text-center mx-2">
                    <img src="https://community.upwork.com/bpyhf24739/attachments/bpyhf24739/New_to_Upwork/112350/1/Hostess%20characters.jpg"
                         class="d-block rounded-circle mx-auto mb-3" width="162"
                         alt="Ralph Edwards">
                    <h5 class="fw-medium fs-lg mb-1">Sheikh Nishu</h5>
                    <p class="fs-sm mb-3">Co-Founder</p>
                    <div class="d-flex justify-content-center">
                        <a href="https://www.facebook.com/sheikhnishu.swe/"
                           class="btn btn-icon btn-outline-secondary btn-facebook btn-sm me-2">
                            <i class="bx bxl-facebook"></i>
                        </a>
                        <a href="https://bd.linkedin.com/in/sheikhnishu"
                           class="btn btn-icon btn-outline-secondary btn-linkedin btn-sm me-2">
                            <i class="bx bxl-linkedin"></i>
                        </a>
                        <a href="https://github.com/sheikhnishu"
                           class="btn btn-icon btn-outline-secondary btn-twitter btn-sm">
                            <i class="bx bxl-github"></i>
                        </a>
                    </div>
                </div>
            </div>

            <!-- Item -->
            <div class="swiper-slide py-3" style="width: 250px; margin: auto">
                <div class="card card-body card-hover bg-light border-0 text-center mx-2">
                    <img src="https://community.upwork.com/bpyhf24739/attachments/bpyhf24739/New_to_Upwork/112350/1/Hostess%20characters.jpg"
                         class="d-block rounded-circle mx-auto mb-3" width="162"
                         alt="Ralph Edwards">
                    <h5 class="fw-medium fs-lg mb-1">Sheikh Nishu</h5>
                    <p class="fs-sm mb-3">Backend Developer</p>
                    <div class="d-flex justify-content-center">
                        <a href="https://www.facebook.com/sheikhnishu.swe/"
                           class="btn btn-icon btn-outline-secondary btn-facebook btn-sm me-2">
                            <i class="bx bxl-facebook"></i>
                        </a>
                        <a href="https://bd.linkedin.com/in/sheikhnishu"
                           class="btn btn-icon btn-outline-secondary btn-linkedin btn-sm me-2">
                            <i class="bx bxl-linkedin"></i>
                        </a>
                        <a href="https://github.com/sheikhnishu"
                           class="btn btn-icon btn-outline-secondary btn-twitter btn-sm">
                            <i class="bx bxl-github"></i>
                        </a>
                    </div>
                </div>
            </div>

            <!-- Item -->
            <div class="swiper-slide py-3" style="width: 250px; margin: auto">
                <div class="card card-body card-hover bg-light border-0 text-center mx-2">
                    <img src="https://community.upwork.com/bpyhf24739/attachments/bpyhf24739/New_to_Upwork/112350/1/Hostess%20characters.jpg"
                         class="d-block rounded-circle mx-auto mb-3" width="162"
                         alt="Cameron Williamson">
                    <h5 class="fw-medium fs-lg mb-1">Sheikh Nishu</h5>
                    <p class="fs-sm mb-3">Frontend Developer</p>
                    <div class="d-flex justify-content-center">
                        <a href="https://www.facebook.com/sheikhnishu.swe/"
                           class="btn btn-icon btn-outline-secondary btn-facebook btn-sm me-2">
                            <i class="bx bxl-facebook"></i>
                        </a>
                        <a href="https://bd.linkedin.com/in/sheikhnishu"
                           class="btn btn-icon btn-outline-secondary btn-linkedin btn-sm me-2">
                            <i class="bx bxl-linkedin"></i>
                        </a>
                        <a href="https://github.com/sheikhnishu"
                           class="btn btn-icon btn-outline-secondary btn-twitter btn-sm">
                            <i class="bx bxl-github"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section>


    <!-- Social networks (Carousel on narrow screens) -->
    <section class="container text-center py-5 my-2 mb-4">
        <h2 class="h1 mb-4">We Have Social Networks</h2>
        <p class="fs-lg text-muted pb-2 mb-5">Follow us and keep up to date with the freshest news!</p>
        <div class="swiper-wrapper">

            <!-- Item -->
            <div class="swiper-slide" style="width: 250px; margin: auto">
                <div class="position-relative text-center border-end mx-n1">
                    <a href="https://www.facebook.com/sheikhnishu.swe/"
                       class="btn btn-icon btn-secondary btn-facebook btn-lg stretched-link">
                        <i class="bx bxl-facebook"></i>
                    </a>
                    <div class="pt-4">
                        <h6 class="mb-1">Facebook</h6>
                        <p class="fs-sm text-muted mb-0">TourGuide</p>
                    </div>
                </div>
            </div>


            <!-- Item -->
            <div class="swiper-slide" style="width: 250px; margin: auto">
                <div class="position-relative text-center border-end mx-n1">
                    <a href="https://www.instagram.com/anik-ronjon/"
                       class="btn btn-icon btn-secondary btn-facebook btn-lg stretched-link">
                        <i class="bx bxl-instagram"></i>
                    </a>
                    <div class="pt-4">
                        <h6 class="mb-1">Instagram</h6>
                        <p class="fs-sm text-muted mb-0">TourGuide</p>
                    </div>
                </div>
            </div>

            <!-- Item -->
            <div class="swiper-slide" style="width: 250px; margin: auto">
                <div class="position-relative text-center border-end mx-n1">
                    <a href="https://github.com/sheikhnishu"
                       class="btn btn-icon btn-secondary btn-instagram btn-lg stretched-link">
                        <i class="bx bxl-github"></i>
                    </a>
                    <div class="pt-4">
                        <h6 class="mb-1">Github</h6>
                        <p class="fs-sm text-muted mb-0">TourGuide</p>
                    </div>
                </div>
            </div>


            <!-- Item -->
            <div class="swiper-slide" style="width: 250px; margin: auto">
                <div class="position-relative text-center border-end mx-n1">
                    <a href="https://bd.linkedin.com/in/sheikhnishu"
                       class="btn btn-icon btn-secondary btn-youtube btn-lg stretched-link">
                        <i class="bx bxl-linkedin"></i>
                    </a>
                    <div class="pt-4">
                        <h6 class="mb-1">Linkedin</h6>
                        <p class="fs-sm text-muted mb-0">TourGuide</p>
                    </div>
                </div>
            </div>

            <!-- Item -->
            <div class="swiper-slide" style="width: 250px; margin: auto">
                <div class="position-relative text-center border-end mx-n1">
                    <a href="https://youtube.com/sheikhnishu"
                       class="btn btn-icon btn-secondary btn-youtube btn-lg stretched-link">
                        <i class="bx bxl-youtube"></i>
                    </a>
                    <div class="pt-4">
                        <h6 class="mb-1">YouTube</h6>
                        <p class="fs-sm text-muted mb-0">TourGuide</p>
                    </div>
                </div>
            </div>

        </div>
    </section>
    {% include 'footer.html' %}
{% endblock %}

tourplan/templates/tourplan/contact.html
{% extends '_base.html' %}


{% block container %}
    {% if not user.is_authenticated %}
        {% include 'navbar.html' %}
    {% else %}
        {% include 'navbar_in_logged_state.html' %}
    {% endif %}
    <!-- Hero -->
    <section class="dark-mode position-relative" style="background-color: #151922;">

        <!-- Content -->
        <div class="container position-relative zindex-2 pt-5 pb-2 pb-md-0">

            <!-- Breadcrumb -->
            <nav class="pt-lg-4" aria-label="breadcrumb">
                <ol class="breadcrumb mb-0">
                    <li class="breadcrumb-item">
                        <a href="{% url 'tourplan:home_page' %}"><i class="bx bx-home-alt fs-lg me-1"></i>Home</a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">Contacts</li>
                </ol>
            </nav>

            <div class="row justify-content-center pt-3 mt-3">
                <div class="col-xl-6 col-lg-7 col-md-8 col-sm-10 text-center">
                    <h1 class="mb-4">Get in Touch</h1>
                    <p class="fs-lg pb-3 mb-3">Have a project in mind? To request a quote contact us directly or fill
                        out the form and let us know how we can help.</p>
                    <div class="d-flex justify-content-center">
                        <a href="https://www.facebook.com/anikronjon.swe/"
                           class="btn btn-icon btn-secondary btn-facebook rounded-circle mx-2">
                            <i class="bx bxl-facebook"></i>
                        </a>
                        <a href="https://github.com/anikronjon"
                           class="btn btn-icon btn-secondary btn-instagram rounded-circle mx-2">
                            <i class="bx bxl-github"></i>
                        </a>
                        <a href="https://bd.linkedin.com/in/anikronjon"
                           class="btn btn-icon btn-secondary btn-google rounded-circle mx-2">
                            <i class="bx bxl-linkedin"></i>
                        </a>
                        <a href="https://developers.google.com/profile/u/anikronjon"
                           class="btn btn-icon btn-secondary btn-google rounded-circle mx-2">
                            <i class="bx bxl-google"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <!-- Bottom shape -->
        <div class="d-flex position-absolute top-100 start-0 w-100 overflow-hidden mt-n5" style="color: #151922;">
            <div class="position-relative start-50 translate-middle-x flex-shrink-0 mt-n5 mt-md-n3 mt-lg-n1"
                 style="width: 3788px;">
                <svg xmlns="http://www.w3.org/2000/svg" width="3788" height="144" viewBox="0 0 3788 144">
                    <path fill="currentColor" d="M0,0h3788.7c-525,90.2-1181.7,143.9-1894.3,143.9S525,90.2,0,0z"/>
                </svg>
            </div>
        </div>
    </section>


    <!-- Email + Phone -->
    <section class="container py-5 my-md-2 my-lg-4 my-xl-5">
        <div class="row justify-content-center pt-5 pb-1 pb-sm-2 pb-md-3">
            <div class="col-xxl-8 col-xl-9 col-lg-10 pt-sm-2 pt-md-5">
                <div class="d-sm-flex">
                    <div class="d-flex flex-column w-sm-50 border-0 bg-transparent text-center px-sm-1 px-md-5 pb-3 pb-sm-0 mb-4 mb-sm-0">
                        <div class="card-body p-0">
                            <div class="d-inline-block bg-secondary text-primary rounded-circle fs-3 lh-1 p-3 mb-3">
                                <i class="bx bx-envelope"></i>
                            </div>
                            <p class="pb-2 pb-sm-3 mb-3">Please feel free to drop us a line. We will respond as soon as
                                possible.</p>
                        </div>
                        <div class="card-footer border-0 p-0">
                            <a href="mailto:anikronjon.swe@gmail.com" class="btn btn-lg btn-primary">Send email</a>
                        </div>
                    </div>
                    <div class="vr text-border d-none d-sm-inline-block m-4"></div>
                    <div class="card w-sm-50 border-0 bg-transparent text-center px-sm-1 px-md-5">
                        <div class="card-body p-0">
                            <div class="d-inline-block bg-secondary text-primary rounded-circle fs-3 lh-1 p-3 mb-3">
                                <i class="bx bx-phone-call"></i>
                            </div>
                            <p class="pb-2 pb-sm-3 mb-3">If you need immediate assistance feel free to call us any
                                time.</p>
                        </div>
                        <div class="card-footer border-0 p-0">
                            <a href="tel:01307191873" class="btn btn-lg btn-primary">Call us</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

tourplan/templates/tourplan/home.html
{% extends '_base.html' %}

{% block title %}{% endblock %}

{% block container %}
    <main class="page-wrapper">
        {% if not user.is_authenticated %}
            {% include 'navbar.html' %}
        {% else %}
            {% include 'navbar_in_logged_state.html' %}
        {% endif %}


        <div class="container">
            <!-- Hero Widget -->
            <!-- Tourist places -->
            <div class="pb-4 mb-4 mt-5">
                <h2 class="">Popular Tourist places</h2>
                <div class="card-group">
                    <div class="card m-2">
                        <a href="{% url 'tourplan:tourplan_list_page' %}">
                            <img class="card-img-top m-auto" style="height: 240px;"
                                 src="https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1b/ed/95/07/limak-eurasia-luxury.jpg?w=700&h=-1&s=1"
                                 alt="Card image">
                        </a>
                        <div class="card-body">
                            <a href="{% url 'tourplan:tourplan_list_page' %}">
                                <h5 class="card-title">See all Places</h5>
                            </a>
                            <p class="card-text fs-sm"></p>
                        </div>
                    </div>
                    {% for tour in tourplans %}
                        <div class="card m-2">
                            <img class="card-img-top m-auto" style="height: 240px;" src="{{ tour.cover_photo.url }}"
                                 alt="Card image">
                            <div class="card-body">
                                <h5 class="card-title">{{ tour.name }}</h5>
                                <p class="card-text fs-sm"></p>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>


            <!-- Hotel -->
            {% if hotels %}
                <div class="pb-4 mb-4">
                    <h2 class="">Popular Hotels</h2>
                    <div class="card-group gap-3">
                        <div class="card m-2">
                            <a href="{% url 'tourplan:hotel_list_page' %}">
                                <img class="card-img-top m-auto" style="height: 240px;"
                                     src="https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1b/ed/95/07/limak-eurasia-luxury.jpg?w=700&h=-1&s=1"
                                     alt="Card image">
                            </a>
                            <div class="card-body">
                                <a href="{% url 'tourplan:hotel_list_page' %}">
                                    <h5 class="card-title">See all Places</h5>
                                </a>
                                <p class="card-text fs-sm"></p>
                            </div>
                        </div>
                        {% for hotel in hotels %}
                            <div class="card">
                                <img class="card-img-top" style="height: 240px;" src="{{ hotel.image.url }}"
                                     alt="Card image">
                                <div class="card-body">
                                    <h5 class="card-title">{{ hotel.name }}</h5>
                                    <p class="card-text fs-sm"></p>
                                </div>
                                <div class="card-footer border-top-0 pt-0">
                                    <a class="btn btn-sm btn-primary" href="#">Go somewhere</a>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% endif %}


            <!-- Restaurant -->
            {% if restaurants %}
                <div class="pb-4 mb-4">
                    <h2>Popular Restaurants</h2>
                    <div class="card-group gap-3 pb-4 mb-2">
                        <div class="card m-2">
                            <a href="{% url 'tourplan:restaurant_list_page' %}">
                                <img class="card-img-top m-auto" style="height: 240px;"
                                     src="https://www.visitphilly.com/wp-content/uploads/2023/08/Enswell-Interior-by-J-Varney-2200x1237px.jpg"
                                     alt="Card image">
                            </a>
                            <div class="card-body">
                                <a href="{% url 'tourplan:restaurant_list_page' %}">
                                    <h5 class="card-title">See all Places</h5>
                                </a>
                                <p class="card-text fs-sm"></p>
                            </div>
                        </div>
                        {% for restaurant in restaurants %}
                            <div class="card">
                                <img class="card-img-top" src="{{ restaurant.image.url }}" alt="Card image"
                                     style="height: 240px;">
                                <div class="card-body">
                                    <h5 class="card-title">{{ restaurant.name }}</h5>
                                    <p class="card-text fs-sm"></p>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% endif %}

        </div>
    </main>
    {% include 'footer.html' %}
{% endblock %}

tourplan/templates/tourplan/tourplan.html
{% extends '_base.html' %}

{% block title %}{% endblock %}

{% block container %}
    <main class="page-wrapper">
        {% if not user.is_authenticated %}
            {% include 'navbar.html' %}
        {% else %}
            {% include 'navbar_in_logged_state.html' %}
        {% endif %}

        <!-- Iframe (Google map) -->
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d8677.265223755709!2d90.318795256187!3d23.877537724709978!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3755b8ada2664e21%3A0x3c872fd17bc11ddb!2sDaffodil%20International%20University!5e0!3m2!1sen!2sbd!4v1689412473042!5m2!1sen!2sbd" width="600" style="border:0;height: 100vh" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>

    </main>
    {% include 'footer.html' %}
{% endblock %}