account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('signin/', views.signin_view, name='signin'),
    path('profile/', views.profile_view, name='profile'),
    path('signout/', views.signout_view, name='signout'),
]

blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'
urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<slug:slug>/', views.PostDetailView.as_view(), name='post_detail'),
    # path('<slug:slug>/like/', views.like_post, name='post_like'),
    # path('<slug:slug>/comment/', views.comment_post, name='post_comment'),
    # path('<slug:slug>/rate/', views.rating_post, name='post_rate'),
]

chat/urls.py
from django.urls import path
from . import views


app_name = 'chat'
urlpatterns = [
    path('group/', views.message_group_view, name='group_page'),
    path('group/<str:group_name>/', views.message_chat_view, name='chat_page'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('', include('tourplan.urls', namespace='tourplan')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('chat/', include('chat.urls', namespace='chat')),
    path('game/', include('game.urls', namespace='game')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

game/urls.py
from django.urls import path
from . import views

app_name = 'game'
urlpatterns = [
    path('', views.game_view, name='game_page'),
]

tourplan/urls.py
from django.urls import path
from . import views

app_name = 'tourplan'
urlpatterns = [
    path('', views.home_view, name='home_page'),
    path('tour/', views.tourplan_view, name='tourplan_list_page'),
    path('tour/<slug:slug>/', views.tourplan_view, name='tourplan_detail_page'),

    path('agency/', views.agency_view, name='agency_list_page'),
    path('hotel/', views.hotel_view, name='hotel_list_page'),
    path('restaurant/', views.restaurant_view, name='restaurant_list_page'),
    path('about/', views.about_view, name='about_page'),
    path('contact/', views.contact_view, name='contact_page'),

    path('map/', views.google_map, name='google_map_page')
]

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>TourGuide</title>

    <!-- SEO Meta Tags -->
    <meta name="description" content="TourGuide">
    <meta name="keywords"
          content="bootstrap, business, creative agency, mobile app showcase, saas, fintech, finance, online courses, software, medical, conference landing, services, e-commerce, shopping cart, multipurpose, shop, ui kit, marketing, seo, landing, blog, portfolio, html5, css3, javascript, gallery, slider, touch, creative">
    <meta name="author" content="Anik Ronjon">

    <!-- Viewport -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Favicon and Touch Icons -->
    <meta name="msapplication-TileColor" content="#080032">
    <meta name="theme-color" content="#ffffff">

    <!-- Vendor Styles -->
{#    <link rel="stylesheet" media="screen" href="{% static '' %}css/boxicons.min.css"/>#}
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css">
    <!-- Main Theme Styles + Bootstrap -->
    <link rel="stylesheet" media="screen" href="{% static '' %}css/theme.min.css">

    <!-- Page loading styles -->
    <style>
        .page-loading {
            position: fixed;
            top: 0;
            right: 0;
            bottom: 0;
            left: 0;
            width: 100%;
            height: 100%;
            -webkit-transition: all .4s .2s ease-in-out;
            transition: all .4s .2s ease-in-out;
            background-color: #fff;
            opacity: 0;
            visibility: hidden;
            z-index: 9999;
        }

        .dark-mode .page-loading {
            background-color: #0b0f19;
        }

        .page-loading.active {
            opacity: 1;
            visibility: visible;
        }

        .page-loading-inner {
            position: absolute;
            top: 50%;
            left: 0;
            width: 100%;
            text-align: center;
            -webkit-transform: translateY(-50%);
            transform: translateY(-50%);
            -webkit-transition: opacity .2s ease-in-out;
            transition: opacity .2s ease-in-out;
            opacity: 0;
        }

        .page-loading.active > .page-loading-inner {
            opacity: 1;
        }

        .page-loading-inner > span {
            display: block;
            font-size: 1rem;
            font-weight: normal;
            color: #9397ad;
        }

        .dark-mode .page-loading-inner > span {
            color: #fff;
            opacity: .6;
        }

        .page-spinner {
            display: inline-block;
            width: 2.75rem;
            height: 2.75rem;
            margin-bottom: .75rem;
            vertical-align: text-bottom;
            border: .15em solid #b4b7c9;
            border-right-color: transparent;
            border-radius: 50%;
            -webkit-animation: spinner .75s linear infinite;
            animation: spinner .75s linear infinite;
        }

        .dark-mode .page-spinner {
            border-color: rgba(255, 255, 255, .4);
            border-right-color: transparent;
        }

        @-webkit-keyframes spinner {
            100% {
                -webkit-transform: rotate(360deg);
                transform: rotate(360deg);
            }
        }

        @keyframes spinner {
            100% {
                -webkit-transform: rotate(360deg);
                transform: rotate(360deg);
            }
        }
    </style>

    <!-- Theme mode -->
    <script>
        let mode = window.localStorage.getItem('mode'),
            root = document.getElementsByTagName('html')[0];
        if (mode !== null && mode === 'dark') {
            root.classList.add('dark-mode');
        } else {
            root.classList.remove('dark-mode');
        }
    </script>

    <!-- Page loading scripts -->
    <script>
        (function () {
            window.onload = function () {
                const preloader = document.querySelector('.page-loading');
                preloader.classList.remove('active');
                setTimeout(function () {
                    preloader.remove();
                }, 1000);
            };
        })();
    </script>

    <!-- Google Tag Manager -->
    <script>
        (function (w, d, s, l, i) {
            w[l] = w[l] || [];
            w[l].push({
                'gtm.start':
                    new Date().getTime(), event: 'gtm.js'
            });
            var f = d.getElementsByTagName(s)[0],
                j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
            j.async = true;
            j.src =
                'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
            f.parentNode.insertBefore(j, f);
        })(window, document, 'script', 'dataLayer', 'GTM-WKV3GT5');
    </script>
</head>
<body>
    {% block container %}
    {% endblock %}
    <!-- Back to top button -->
    <a href="landing-startup.html#top" class="btn-scroll-top" data-scroll>
      <span class="btn-scroll-top-tooltip text-muted fs-sm me-2">Top</span>
      <i class="btn-scroll-top-icon bx bx-chevron-up"></i>
    </a>


    <!-- Vendor Scripts -->
    <script src="{% static '' %}js/bootstrap.bundle.min.js"></script>
    <script src="{% static '' %}js/smooth-scroll.polyfills.min.js"></script>
    <script src="{% static '' %}js/parallax.min.js"></script>
    <script src="{% static '' %}js/rellax.min.js"></script>

    <!-- Main Theme Script -->
    <script src="{% static '' %}js/theme.min.js"></script>
</body>
</html>

templates/footer.html
{% load static %}
<footer class="footer dark-mode bg-dark border-top border-light py-5">
    <div class="container pt-2 pt-sm-4">
        <div class="row">
            <div class="col-md-6 col-lg-5 col-xl-4 pb-2 pb-sm-3 pb-md-0 mb-4 mb-md-0">
                <div class="navbar-brand text-dark p-0 me-0 mb-3 mb-lg-4">
                    TourGuide
                </div>
                <p class="mb-0">We are guide people so that our user can easily find there destination.</p>
            </div>
            <div class="col-md-6 col-xxl-5 offset-lg-1 offset-xl-2 offset-xxl-3">
                <div class="row row-cols-1 row-cols-sm-2">
                    <div class="col pb-2 pb-sm-0 mb-4 mb-sm-0">
                        <h3 class="h5 pb-1 pb-sm-2 pb-lg-3">Contact us</h3>
                        <ul class="nav flex-column mb-3">
                            <li>
                                <a href="tel:01682717766" class="nav-link fs-lg fw-normal px-0 py-1">
                                    <i class="bx bx-phone-call fs-4 me-2"></i>
                                    016 82717766
                                </a>
                            </li>
                            <li>
                                <a href="mailto:email@example.com" class="nav-link fs-lg fw-normal px-0 py-1">
                                    <i class="bx bx-envelope fs-4 me-2"></i>
                                    nishumony420@gmail.com
                                </a>
                            </li>
                        </ul>
                        <div class="d-flex pt-2 pt-sm-3 pt-md-4">
                            <a href="https://www.facebook.com/sheikhnishu/"
                               class="btn btn-icon btn-secondary btn-facebook rounded-circle me-3">
                                <i class="bx bxl-facebook"></i>
                            </a>
                            <a href="https://bd.linkedin.com/in/sheikhnishu"
                               class="btn btn-icon btn-secondary btn-linkedin rounded-circle me-3">
                                <i class="bx bxl-linkedin"></i>
                            </a>
                            <a href="https://github.com/sheikhnishu"
                               class="btn btn-icon btn-secondary btn-telegram rounded-circle me-3">
                                <i class="bx bxl-github"></i>
                            </a>
                            <a href="https://developers.google.com/profile/u/sheikhnishu"
                               class="btn btn-icon btn-secondary btn-youtube rounded-circle me-3">
                                <i class="bx bxl-google"></i>
                            </a>
                        </div>
                    </div>
                    <div class="col ps-sm-4 ps-md-5">
                        <h3 class="h5 pb-1 pb-sm-2 pb-lg-3">Country</h3>
                        <div class="nav dropdown">
                            <a class="nav-link dropdown-toggle fs-lg fw-normal px-0 py-1"
                               data-bs-toggle="dropdown">
                                USA
                            </a>
                            <div class="dropdown-menu my-1">
                                <a class="dropdown-item fs-base pb-1">
                                    France
                                </a>
                                <a  class="dropdown-item fs-base pb-1">
                                    Germany
                                </a>
                                <a class="dropdown-item fs-base pb-1">
                                    Italy
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <p class="nav d-block fs-sm pt-5 mb-0">
            <span class="text-light opacity-60">© All rights reserved. Made by </span>
            <a class="nav-link d-inline-block p-0" href="http://sheikhnishu.com" target="_blank" rel="noopener">Sheikh Nishu</a>
        </p>
    </div>
</footer>

templates/navbar.html
{% load static %}
<header class="navbar navbar-expand-lg bg-light shadow-sm">
    <div class="container">
        <a href="{% url 'tourplan:home_page' %}" class="navbar-brand">
            TourGuide
        </a>
        <button class="navbar-toggler ms-auto" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse2"
                aria-expanded="false">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="form-check form-switch mode-switch order-lg-2 ms-4 ms-lg-auto me-lg-4" data-bs-toggle="mode">
            <input type="checkbox" class="form-check-input" id="theme-mode">
            <label class="form-check-label d-none d-sm-block d-lg-none d-xl-block" for="theme-mode">Light</label>
            <label class="form-check-label d-none d-sm-block d-lg-none d-xl-block" for="theme-mode">Dark</label>
        </div>
        <a href="{% url 'account:signin' %}" class="btn btn-secondary btn-sm fs-sm rounded order-lg-3 d-none d-lg-inline-flex">
            <img src="https://community.upwork.com/bpyhf24739/attachments/bpyhf24739/New_to_Upwork/112350/1/Hostess%20characters.jpg" alt="profile">
            <i class="bx bx-log-in fs-lg me-2"></i>
            Sign in
        </a>
        <nav id="navbarCollapse2" class="collapse navbar-collapse">
            <hr class="d-lg-none mt-3 mb-2">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a href="{% url 'tourplan:google_map_page' %}" class="nav-link">Map</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'blog:post_list' %}" class="nav-link">Blog</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'game:game_page' %}" class="nav-link">Game</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'chat:group_page' %}" class="nav-link">Chat</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'tourplan:about_page' %}" class="nav-link">About</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'tourplan:contact_page' %}" class="nav-link">Contact</a>
                </li>
            </ul>
            <a href="{% url 'account:signin' %}" class="btn btn-secondary btn-sm fs-sm rounded my-3 d-lg-none">
                <i class="bx bx-log-in fs-lg me-2"></i>
                Sign in
            </a>
        </nav>
    </div>
</header>

templates/navbar_in_logged_state.html
{% load static %}
<header class="navbar navbar-expand-lg bg-light shadow-sm">
    <div class="container">
        <a href="{% url 'tourplan:home_page' %}" class="navbar-brand">
            TourGuide
        </a>
        <button class="navbar-toggler ms-auto" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse5"
                aria-expanded="false">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="nav dropdown d-block order-lg-3 ms-4">
            <a href="#" class="d-flex nav-link p-0" data-bs-toggle="dropdown">
                <img src="https://community.upwork.com/bpyhf24739/attachments/bpyhf24739/New_to_Upwork/112350/1/Hostess%20characters.jpg" class="rounded-circle" width="48" alt="Avatar">
                <div class="d-none d-sm-block ps-2">
                    <div class="fs-xs lh-1 opacity-60">Hello,</div>
                    <div class="fs-sm dropdown-toggle">{{ user }}</div>
                </div>
            </a>
            <ul class="dropdown-menu dropdown-menu-end my-1" style="width: 14rem;">
                <li>
                    <a href="{% url 'account:profile' %}" class="dropdown-item d-flex align-items-center">
                        <i class="bx bx-chat fs-base opacity-60 me-2"></i>
                        Profile
                    </a>
                </li>
                <li>
                    <a href="#" class="dropdown-item d-flex align-items-center">
                        <i class="bx bx-group fs-base opacity-60 me-2"></i>
                        Followers
                        <span class="ms-auto fs-xs text-muted">146</span>
                    </a>
                </li>
                <li class="dropdown-divider"></li>
                <li>
                    <a class="dropdown-item d-flex align-items-center" href="{% url 'account:signout' %}">
                        <i class="bx bx-log-out fs-base opacity-60 me-2"></i>
                        Sign out
                    </a>
                </li>
            </ul>
        </div>
        <nav id="navbarCollapse5" class="collapse navbar-collapse order-lg-2">
            <hr class="d-lg-none mt-3 mb-2">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a href="{% url 'tourplan:google_map_page' %}" class="nav-link">Map</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'blog:post_list' %}" class="nav-link">Blog</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'game:game_page' %}" class="nav-link">Game</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'chat:group_page' %}" class="nav-link">Chat</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'tourplan:about_page' %}" class="nav-link">About</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'tourplan:contact_page' %}" class="nav-link">Contact</a>
                </li>
            </ul>
        </nav>
    </div>
</header>